<a href="https://colab.research.google.com/github/HariBejju/ML_DL_AI/blob/main/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 60.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 74.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 15.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
tsfresh 0.21.0 requires scipy>=1.14.0;

In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [4]:
wv["cricket"]

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [6]:
wv["Dhoni"]

array([ 0.04858398,  0.19335938, -0.02624512,  0.33984375, -0.01806641,
       -0.4921875 ,  0.26757812, -0.328125  ,  0.04785156, -0.05834961,
        0.05737305, -0.21777344,  0.16992188,  0.14355469, -0.16113281,
        0.22265625, -0.05859375, -0.25976562,  0.10498047,  0.24316406,
        0.12402344, -0.46875   , -0.01611328, -0.29492188, -0.01696777,
        0.09130859, -0.25585938,  0.01843262,  0.49023438, -0.4375    ,
       -0.30273438, -0.06787109, -0.13574219,  0.0009079 , -0.10449219,
        0.12792969, -0.35742188,  0.20800781,  0.43164062, -0.12158203,
        0.3984375 , -0.06494141,  0.515625  ,  0.22949219, -0.08544922,
       -0.34765625,  0.01257324, -0.06982422,  0.23730469,  0.25585938,
       -0.00274658,  0.20996094, -0.06738281, -0.25976562, -0.0055542 ,
       -0.1953125 ,  0.02832031, -0.47265625, -0.3359375 , -0.30664062,
        0.32226562,  0.26367188, -0.33007812, -0.17480469,  0.15820312,
        0.41210938,  0.06787109, -0.22949219,  0.2265625 ,  0.09

In [7]:
wv["Kohli"]

array([-2.75390625e-01,  4.45312500e-01, -1.06445312e-01,  1.67968750e-01,
       -2.48046875e-01, -3.80859375e-01,  3.43750000e-01, -1.48437500e-01,
       -3.66210938e-02, -3.78417969e-02,  5.51757812e-02, -5.02929688e-02,
        5.34667969e-02, -1.14257812e-01, -6.64062500e-02,  1.45507812e-01,
        2.02148438e-01, -3.08593750e-01, -2.05078125e-01,  1.39648438e-01,
       -2.35595703e-02, -2.18750000e-01,  2.79296875e-01, -8.98437500e-02,
        1.95312500e-01, -6.10351562e-02, -3.55468750e-01, -3.10058594e-02,
        1.38671875e-01, -9.61914062e-02, -5.83496094e-02, -3.00781250e-01,
        1.69677734e-02, -1.35742188e-01, -2.96875000e-01, -8.64257812e-02,
       -1.43554688e-01, -3.14453125e-01,  2.42187500e-01, -2.53906250e-01,
        1.20605469e-01,  2.83203125e-02, -5.39550781e-02,  3.00781250e-01,
       -7.22656250e-02, -3.02734375e-01, -4.22363281e-02,  6.93359375e-02,
        4.29687500e-01, -5.10253906e-02,  1.66992188e-01, -2.02148438e-01,
       -5.00488281e-02, -

In [8]:
wv.most_similar("Dhoni")

[('Dravid', 0.8947852849960327),
 ('Yuvraj', 0.8731703162193298),
 ('MS_Dhoni', 0.8722649216651917),
 ('Sehwag', 0.8716583847999573),
 ('Mahendra_Singh_Dhoni', 0.8672016859054565),
 ('Tendulkar', 0.8650850057601929),
 ('Ganguly', 0.8535355925559998),
 ('Kumble', 0.8398670554161072),
 ('Sangakkara', 0.8360788226127625),
 ('Rahul_Dravid', 0.8301846385002136)]

In [10]:
wv.most_similar("World_Cup")

[('World_Cups', 0.7915067672729492),
 ('Confederations_Cup', 0.7571763396263123),
 ('FIFA_Confederations_Cup', 0.7164061069488525),
 ('Champions_Trophy', 0.6941148042678833),
 ('Confed_Cup', 0.685827910900116),
 ('WorldCup', 0.6853875517845154),
 ('Fifa_Confederations_Cup', 0.6808676719665527),
 ('####World_Cup', 0.6620058417320251),
 ('quadrennial_showpiece', 0.654705822467804),
 ('Copa_America', 0.6536746621131897)]

In [12]:
wv.similarity("cricket","sports")

0.40087253

In [13]:
vec = wv["king"] - wv["man"] + wv["woman"]

In [14]:
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [15]:
wv.most_similar(vec)

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]